apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnect
metadata:
  name: my-connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 3.0.0
  replicas: 2
  bootstrapServers: my-cluster-kafka-bootstrap:9092
  build:
    output:
      type: docker
      image: "image-registry.openshift-image-registry.svc:5000/streams/kafka-connect-build:latest"
    plugins:
      - name: debezium-connector-sqlserver
        artifacts:
          - type: zip
            url: "https://maven.repository.redhat.com/ga/io/debezium/debezium-connector-sqlserver/1.7.2.Final-redhat-00003/debezium-connector-sqlserver-1.7.2.Final-redhat-00003-plugin.zip"
          - type: zip
            url: "https://maven.repository.redhat.com/ga/io/apicurio/apicurio-registry-distro-connect-converter/2.0.2.Final-redhat-00001/apicurio-registry-distro-connect-converter-2.0.2.Final-redhat-00001.zip"
          - type: zip
            url: "https://maven.repository.redhat.com/ga/io/debezium/debezium-scripting/1.7.2.Final-redhat-00003/debezium-scripting-1.7.2.Final-redhat-00003.zip"
  config:
    group.id: connect-cluster
    offset.storage.topic: connect-cluster-offsets
    config.storage.topic: connect-cluster-configs
    status.storage.topic: connect-cluster-status
