kind: ConfigMap
apiVersion: v1
metadata:
  name: moon-data-sql
data:
  moon-data.sql: |-
    CREATE TABLE IF NOT EXISTS Orders
    (
        OrderId INTEGER PRIMARY KEY,
        OrderType VARCHAR(1) NOT NULL,
        OrderItemName VARCHAR(50) NOT NULL,
        Quantity INTEGER NOT NULL,
        Price VARCHAR(50) NOT NULL,
        ShipmentAddress VARCHAR(100) NOT NULL,
        ZipCode VARCHAR(10) NOT NULL,
        OrderUser VARCHAR(10) NOT NULL
    );
