metadata:
  name: ${project.artifactId}-configmap
data:
  application.yml: |-
    spring:
      datasource:
        url: jdbc:postgresql://postgresql.moon.svc:5432/sampledb
    camel:
      component:
        kafka.configuration:
          brokers: "my-cluster-kafka-bootstrap:9092"
